# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FindReplace
                                 A QGIS plugin
 Simple screen to quickly perform find/replace on text in columns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-31
        copyright            : (C) 2020 by Sem Riemens
        email                : semriemens@posteo.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FindReplace class from file FindReplace.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .findreplace import FindReplace
    return FindReplace(iface)
